### PR TITLE
add validation input and hint BMI dialog

### PR DESCRIPTION
**Pull request by irvanalfaridzi**

### CODE REVIEW

**Comment by viveeeeeek** [comment]
Awesome @irvanalfaridzi 👍🏼

**Comment by viveeeeeek** [comment]
If you are looking forward for more contributions to flutter apps.
You can check out [this GitHub repo too](https://github.com/viveeeeeek/1stHacktoberfest)!

**Comment by irvanalfaridzi** [comment]
> Awesome @irvanalfaridzi 👍🏼

thanks, you too 👍🏼 

> If you are looking forward for more contributions to flutter apps. You can check out [this GitHub repo too](https://github.com/viveeeeeek/1stHacktoberfest)!

yesterday I have made some PR on that repo but I don't know somehow until now you don't accept my PR, maybe because there is some conflict, but I just fixed it and send a new PR I guest.. please check my new PR maybe there's a problem that I haven't solved yet, this is my first time to contribute on someone repo and make some PR, thank you

**Comment by viveeeeeek** [comment]
yup. I've merged your PR already.

**Comment by irvanalfaridzi** [comment]
> yup. I've merged your PR already.

Cool 😁 thanks 👍🏻

**Pull request merged**
