### PR TITLE
#9 Added Dropdown's

### PR DESCRIPTION
**Pull request by Perumallpardhiv**
#9 
Added 2 Dropdown's for both height and width respectively to change the input values units according to user
And also added functionality according to selected option in dropdown.

Below given are Screenshots after implementing the dropdown feature

### CODE REVIEW

**Comment by Perumallpardhiv** [comment]
@viveeeeeek
pls review my pull request and let me know if any changes required asap

**Comment by viveeeeeek** [comment]
Nice work @Perumallpardhiv. Wish you all the best with your hacktoberfest 2022 journey.

**Comment by Perumallpardhiv** [comment]
> Nice work @Perumallpardhiv. ish you all the best with your hacktoberfest 2022 journey.

Thank you @viveeeeeek sir
Pls provide your discord account so, that I can contact you there if I have any doubts

**Comment by viveeeeeek** [comment]
Welcome. Most of the time I dont use discord but you can connect with me on [Instagram](https://www.instagram.com/viveeeeeek/). <3

**Pull request merged**
